# Generated by Django 4.0.4 on 2022-04-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.AddField(
            model_name='brand',
            name='url',
            field=models.CharField(default='https://www.o2.co.uk/iphone', max_length=100),
            preserve_default=False,
        ),
    ]
