# Generated by Django 4.0.4 on 2022-05-02 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_image'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Specification',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('spec_type', models.CharField(choices=[('diagonal length', 'Diag Size')], max_length=100)),
        #         ('spec_value', models.JSONField()),
        #         ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_specifications', to='products.product')),
        #     ],
        # ),
    ]
