# Generated by Django 4.0.4 on 2022-05-03 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_specification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_type', models.CharField(choices=[('% off', 'Percent'), ('£ off', 'Fixed'), ('buy 1 get 1 free', 'B1G1F')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('sale_start_date', models.DateField()),
                ('sale_end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='temp description', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='on_sale',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='order_limit',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AddField(
            model_name='product',
            name='release_date',
            field=models.DateField(default="2022-01-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='standard_price',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stock_count',
            field=models.IntegerField(blank=True, default=100),
        ),
        # migrations.AddConstraint(
        #     model_name='specification',
        #     constraint=models.UniqueConstraint(fields=('product', 'spec_type'), name='non_fungible_spec_product_pairs'),
        # ),
        migrations.AddField(
            model_name='saleproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_sales', to='products.product'),
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_products', to='products.sale'),
        ),
    ]
