# Generated by Django 4.0.4 on 2022-05-03 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_sale_saleproduct_product_description_product_on_sale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='release_date',
        ),
    ]
