# Generated by Django 4.0.4 on 2022-05-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='sale_end_date',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sale_start_date',
        ),
    ]
