# Generated by Django 4.0.4 on 2022-05-03 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_sale_sale_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionalSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnconditionalSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sale_type', models.CharField(choices=[('% off', 'Percent'), ('£ off', 'Fixed')], max_length=100)),
                ('discount', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='current_price',
            field=models.FloatField(default=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_products', to='products.unconditionalsale'),
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
