# Generated by Django 4.0.4 on 2022-05-03 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_conditionalsale_unconditionalsale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleproduct',
            name='sale',
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='unconditional_sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unconditional_sale_products', to='products.unconditionalsale'),
        ),
    ]
