# Generated by Django 4.0.4 on 2022-05-03 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_saleproduct_sale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discount_type', models.CharField(choices=[('% off', 'Percent'), ('£ off', 'Fixed')], max_length=100)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DiscountProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('discount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_products', to='products.discount')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_discounts', to='products.product')),
            ],
        ),
        migrations.RenameModel(
            old_name='ConditionalSale',
            new_name='Offer',
        ),
        migrations.DeleteModel(
            name='SaleProduct',
        ),
        migrations.DeleteModel(
            name='UnconditionalSale',
        ),
    ]
