# Generated by Django 4.0.4 on 2022-05-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_discount_discountproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='on_sale',
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('buy 1 get 1 free', 'B1G1F')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_price',
            field=models.FloatField(blank=True),
        ),
    ]
