# Generated by Django 4.0.4 on 2022-05-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_offerproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='label',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
