# Generated by Django 4.0.4 on 2022-05-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_basketdiscount_and_more'),
        ('products', '0013_image_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerproduct',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='offerproduct',
            name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='standard_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='current_price',
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_code',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('% off', 'Percent'), ('£ off', 'Fixed'), ('buy 1 get 1 free', 'B1G1F')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='OfferProduct',
        ),
    ]
