# Generated by Django 4.0.4 on 2022-05-08 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_offerproduct_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_discounts', to='products.product', unique=True),
        ),
    ]
