# Generated by Django 4.0.4 on 2022-05-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='order_limit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_count',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='order_limit',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='stock_count',
            field=models.IntegerField(blank=True, default=100),
        ),
    ]
