# Generated by Django 4.0.4 on 2022-05-09 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_product_order_limit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='color',
            new_name='colour',
        ),
    ]
