# Generated by Django 4.0.4 on 2022-05-09 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_image_product_image_product_varient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='product_varient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variant_images', to='products.productvariant'),
        ),
    ]
