# Generated by Django 4.0.4 on 2022-05-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_image_product_varient'),
    ]

    operations = [
        # migrations.RemoveConstraint(
        #     model_name='specification',
        #     name='non_fungible_spec_product_pairs',
        # ),
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/brands'),
        ),
        # migrations.AddConstraint(
        #     model_name='productvariant',
        #     constraint=models.UniqueConstraint(fields=('product', 'colour', 'storage'), name='unique_variants'),
        # ),
    ]
