# Generated by Django 4.0.4 on 2022-05-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_remove_specification_non_fungible_spec_product_pairs_and_more'),
    ]

    operations = [
        # migrations.AddConstraint(
        #     model_name='specification',
        #     constraint=models.UniqueConstraint(fields=('product', 'spec_type'), name='non_fungible_spec_product_pairs'),
        # ),
    ]
