# Generated by Django 4.0.4 on 2022-05-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_specification_non_fungible_spec_product_pairs'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.CharField(default='', max_length=2000),
        ),
        # migrations.DeleteModel(
        #     name='Specification',
        # ),
    ]
