# Generated by Django 4.0.4 on 2022-05-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_product_specifications_delete_specification'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'colour', 'storage'), name='unique_variants'),
        ),
    ]
