# Generated by Django 4.0.4 on 2022-05-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_productvariant_unique_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
