# Generated by Django 4.0.4 on 2022-05-19 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_remove_productvariant_unique_variants_and_more'),
    ]

    operations = [
        # migrations.RemoveConstraint(
        #     model_name='productstorages',
        #     name='unique_storages',
        # ),
    ]
