# Generated by Django 4.0.4 on 2022-05-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_remove_productstorages_unique_storages'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='unique_variants',
        ),
        migrations.AddConstraint(
            model_name='productstorages',
            constraint=models.UniqueConstraint(fields=('product_variant', 'storage'), name='unique_storages'),
        ),
    ]
