# Generated by Django 4.0.4 on 2022-05-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_remove_productvariant_unique_variants_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'colour'), name='unique_variant'),
        ),
    ]
