# Generated by Django 4.0.4 on 2022-05-20 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_alter_brand_image_alter_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='product_varient',
            new_name='product_variant',
        ),
    ]
