# Generated by Django 4.0.4 on 2022-05-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_rename_product_varient_image_product_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
