# Generated by Django 4.0.4 on 2022-05-04 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_offerproduct'),
        ('orders', '0003_rename_price_basket_total_basketoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('basket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket_products', to='orders.basket')),
                ('basket_offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket_offer_products', to='orders.basketoffer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_baskets', to='products.product')),
            ],
        ),
    ]
