# Generated by Django 4.0.4 on 2022-05-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_basketproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='total',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
