# Generated by Django 4.0.4 on 2022-05-05 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_offerproduct'),
        ('orders', '0005_alter_basket_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket_products', to='orders.basket')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_baskets', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='OfferBasketProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='basketoffer',
            name='savings',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='BasketProducts',
        ),
        migrations.AddField(
            model_name='offerbasketproduct',
            name='basket_offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket_offer_products', to='orders.basketoffer'),
        ),
        migrations.AddField(
            model_name='offerbasketproduct',
            name='basket_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket_product_offers', to='orders.basketproduct'),
        ),
    ]
