# Generated by Django 4.0.4 on 2022-05-05 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_offerproduct'),
        ('orders', '0006_basketproduct_offerbasketproduct_basketoffer_savings_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderProducts',
            new_name='OrderProduct',
        ),
    ]
