# Generated by Django 4.0.4 on 2022-05-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_orderproducts_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='offerbasketproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
