# Generated by Django 4.0.4 on 2022-05-08 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_image_label'),
        ('orders', '0008_basketproduct_quantity_offerbasketproduct_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savings', models.FloatField(default=0, null=True)),
                ('basket', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket_dicount', to='orders.basket')),
                ('discount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_baskets', to='products.discount')),
            ],
        ),
        migrations.RemoveField(
            model_name='offerbasketproduct',
            name='basket_offer',
        ),
        migrations.RemoveField(
            model_name='offerbasketproduct',
            name='basket_product',
        ),
        migrations.DeleteModel(
            name='BasketOffer',
        ),
        migrations.DeleteModel(
            name='OfferBasketProduct',
        ),
    ]
