# Generated by Django 4.0.4 on 2022-05-13 14:32

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_remove_specification_non_fungible_spec_product_pairs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0011_alter_basket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='basketproduct',
            name='product_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variant_baskets', to='products.productvariant'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='user',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_basket', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
