# Generated by Django 4.0.4 on 2022-05-16 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_address_order_contact_email_order_contact_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('estimate', models.IntegerField(default=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='contact_email',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='order pending', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_orders', to='orders.delivery'),
        ),
    ]
