# Generated by Django 4.0.4 on 2022-05-16 21:43

import annoying.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_delivery_remove_order_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketdiscount',
            name='basket',
            field=annoying.fields.AutoOneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket_discount', to='orders.basket'),
        ),
    ]
