# Generated by Django 4.0.4 on 2022-05-16 22:04

import annoying.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_basketdiscount_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketdiscount',
            name='id',
        ),
        migrations.AlterField(
            model_name='basketdiscount',
            name='basket',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='basket_discount', serialize=False, to='orders.basket'),
        ),
    ]
