# Generated by Django 4.0.4 on 2022-05-16 22:27

import annoying.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_basketdiscount_basket'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='basketdiscount',
        #     name='id',
        # ),
        migrations.AlterField(
            model_name='basketdiscount',
            name='basket',
            field=annoying.fields.AutoOneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='basket_discount', serialize=False, to='orders.basket'),
            preserve_default=False,
        ),
    ]
