# Generated by Django 4.0.4 on 2022-05-19 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_remove_productvariant_order_limit_and_more'),
        ('orders', '0020_remove_basketdiscount_id_alter_basketdiscount_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketproduct',
            name='product_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variant_baskets', to='products.productstorage'),
        ),
    ]
