# Generated by Django 4.0.4 on 2022-05-21 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_basketproduct_product_variant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketproduct',
            old_name='product_variant',
            new_name='product_storage',
        ),
    ]
