# Generated by Django 4.0.4 on 2022-05-21 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_rename_product_varient_image_product_variant'),
        ('orders', '0022_rename_product_variant_basketproduct_product_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_orders', to='products.productstorage'),
        ),
    ]
